In [37]:
import numpy as np
X=np.array([[[1,2,3,4],[1,3,4,5],[3,7,8,9]]])
print(X)


[[[1 2 3 4]
  [1 3 4 5]
  [3 7 8 9]]]


In [38]:
X.shape[2]

4

In [15]:
X[1]

array([1, 3, 4, 5])

In [40]:
X[0]

array([[1, 2, 3, 4],
       [1, 3, 4, 5],
       [3, 7, 8, 9]])

In [27]:
X[]

IndexError: index 3 is out of bounds for axis 0 with size 3